title: Underdeveloped Writings
author: NexusSpechtor
email: lookshyboy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An attempt at documenting the joys & sorrows of writing a manual on how to use a website
  that is under development & change implemented with little to no fanfare

# social links
github_username:  NexusSpechtor

show_excerpts: false # set to false to remove excerpts on the homepage
